### ISSUE TITLE
dF F0 gives error 'bool' object has no attribute 'all'

### ISSUE THREAD

**Issue by IlsevO** [kushalkolar/MESmerize#100]
Hi,

When I wanted to do the caiman detrend after performing motion correction and CNMF I got an attribute error saying that 'bool' object has no attribute 'all'. I do not have much experience with Mesmerize and python and do not know how to fix this.

**Comment by kushalkolar** [comment]
@IlsevO thanks for posting the issue, however I cannot help you if you do not provide all the information from the issue template.
