### ISSUE TITLE
ImageJ ROIs fileTraceback

### ISSUE THREAD

**Issue by Robkozol** [kushalkolar/MESmerize#108]
Hello,

I am new to mesmerize and currently trying to import GCaMP time series.tif and roi.zip from fiji. I have encountered an error when importing the ROI that seems to implicate a problem with the x axis coordinates (see attached screen shot). I am attaching .zip and screenshot, the tiff zipped is too large to upload. Please let me know a method for sending the tiff (zipped version is 40 mb).

Thanks,
Rob
[RoiSet003.zip](https://github.com/kushalkolar/MESmerize/files/9550830/RoiSet003.zip)
![roiError](https://user-images.githubusercontent.com/26252970/189729310-3242d0a1-49f7-4099-a0a9-8d43d9c748d7.png)

**Comment by kushalkolar** [comment]
I'm pretty sure that only polygon and maybe freehand ROIs are supported

**Comment by Robkozol** [comment]
Worked! thanks! : )
