### ISSUE TITLE
[INSTALLATION HELP Numpy error during pip install mesmerize ]

### ISSUE THREAD

**Issue by ambtetl** [kushalkolar/MESmerize#110]
I know this is the legacy program, but this project was previously started with this version vs mesmerize-core. The entire output of the step with the error results in the comment being too long. I am just adding the specific error line. I can add additional comments for the full output. 

**System information**
1. MacOS Ventura 13.2.1
2. CPU  10 core
3. RAM 64GB
4. Do you have an SSD or magnetic HDD 1TB SSD

**Copy & paste the entire output of the terminal while you were trying to install when the issue came up:**

(mesmerize2) tetloa01@sigure01-studio ~ % pip install mesmerize                            

```
      note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(mesmerize2) tetloa01@sigure01-studio ~ % 

```

**Installation method**
1. Are you using anaconda, python virtual environments, or something else?
  -> if using conda, what is the conda version
conda 3.22.0
2. If you're installing mesmerize through pip, what version of pip is installed in the environment?
pip 23.0.1
3. Are you trying to install in developer mode from the repo?
no
4. What is the python version in the environment you're trying to install `mesmerize` in?
mesmerize2
5. Information if you're using some other installation method. 
Caiman is installed using mamba as conda had a terminal loading screen for >12hours.

**Comment by kushalkolar** [comment]
the dependencies are probably very out of date since the mesmerize desktop app has no CI, your best bet is to try with python3.6 or use the VM.
