### ISSUE TITLE
[BUG] <PeakDetect_AttributeError>

### ISSUE THREAD

**Issue by sorayascuderi** [kushalkolar/MESmerize#111]
**Describe the bug**
Hi @kushalkolar , I know you have a new version of Mesmerize but I'm still using the old version Mesmerize, virtual box on a cluster. It helps me a lot considering I'm not able to code at high level. So far, it works pretty ok for many of the analyses.  Except today when I tried to run in the Flowchart the PeakDetect node, apply and it bugs/stops because an exception occurs. 
All the previous steps needed for the analysis, from cleaning the signal to obtain the Derivative work fine, all the nodes Load_Proj_Df>node Butterworth>Normalization>Derivative generate a transmission object. All pass and are green. 

When I click apply to Peak_Detection it stop and the following error is displayed

Exception:tuple
type <class 'AttributeError'>
AttributeError 'DataFrame' object has no attribute 'set_value'

Steps to reproduce the behavior, for example:

**Expected behavior**
I should visualize on the curves detected, bases and peaks from a dataframe. I tried  previously in another virtual box installed on my laptop and it worked, it took sometime around 15 min, but it worked. Instead on the cluster I'm not able to make it work. 

**Copy paste message from the error window (if any)**
Exception:tuple
type <class 'AttributeError'>
AttributeError 'DataFrame' object has no attribute 'set_value'
The last traceback 
File "/gpfs/gibbs/project/vaccarino/ss2793/conda_envs/mesmerize/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)

**Copy-paste or take a screenshot of the terminal that Mesmerize is running in**
```
<img width="1440" alt="Screen Shot 2023-09-18 at 4 03 32 PM" src="https://github.com/kushalkolar/MESmerize/assets/145394350/3fd45c4a-0fb1-43cc-8e93-38b064cd7da1">


_Make sure the entire stack trace is visible, and all messages relevant to the issue are visible._

**If relevant, messages from the batch manager terminal**

**Screenshots**

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - Conda23.7.2, 6CPU, 25GB per CPU
 -
**Details about your Mesmerize install**
 This is how I launch the Mesmerize on the cluster thanks to the help of a brilliant computational Research Support Analyst  at the Uni that create a yaml file for mezmerize installation for me

module purge
module load cuDNN/8.2.1.32-CUDA-11.3.1
module load Mesa/20.2.1-GCCcore-10.2.0
module load miniconda
conda activate mesmerize
caimanmanager.py install --force
mesmerize

**Environment**
 - Please provide a list of installed packages and their versions, run `pip list` in your environment
 ```
 PASTE OUTPUT OF `pip list` HERE
 ```
 - If you are using a `conda` environment, please also provide a list of conda packages by running `conda list` in your environment
 ```
 ```


**Additional context**
I hope you or someone that had the same issue can help me solving it.

**Comment by kushalkolar** [comment]
I'm pretty sure `DataFrame.set_value()` was removed from `pandas` a while ago. You can try pandas v0.25 or v0.24.
