### ISSUE TITLE
Need help using Mesmerize

### ISSUE THREAD

**Issue by maxrioux100** [kushalkolar/MESmerize#15]
First of all, im on ubuntu 20.04 LTS FRESH INSTALL only for this.
I tried both installation method but I would prefer to make the github one work (since it has less limitations)

When I open mesmerize from the snap installation. I get [Errno 13] permission denied joblib will operate in serial mode. 
I tried to give all the right to /dev/shm but the error persist.

On the other hand. with thee github installation everything looks fine(except for some numpy warning when running python setup.py build_ext -i)

However I cant seem to make the motion correction work. The tif file load perfectly and the batch manager receive it but it always end up red or orange.

![99421166_247618876657099_7303926636599050240_n](https://user-images.githubusercontent.com/40430512/82578608-98bb6000-9b5a-11ea-9a30-090f09253c1a.png)

How can I solve this and complete it.

Thanks a lot

**Comment by kushalkolar** [comment]
Can you click on the batch item to display the output. Can you also give me a screenshot of the system config window. http://mesmerizelab.org/user_guides/general/misc.html#system-configuration

**Comment by maxrioux100** [comment]
![Screenshot from 2020-05-21 13-32-39](https://user-images.githubusercontent.com/40430512/82587723-ae835200-9b67-11ea-861d-0ef3c7660b77.png)
![Screenshot from 2020-05-21 13-32-26](https://user-images.githubusercontent.com/40430512/82587730-af1be880-9b67-11ea-91ec-00257e641a71.png)

**Comment by kushalkolar** [comment]
Did you install using the snap branch?

**Comment by maxrioux100** [comment]
yes as you said in the guide

> Clone the mesmerize repo and enter it:
> 
> git clone https://github.com/kushalkolar/MESmerize.git
> cd MESmerize
> 
> Checkout the snap branch:
> 
> git checkout snap
> 
>

**Comment by kushalkolar** [comment]
I think you need to add the following lines to your system config:

`export PATH=<path to python environment for mesmerize`
`export PYTHONPATH=<path to MESmerize dir>`

See the points about "Pre-run commands" here for more details: http://mesmerizelab.org/user_guides/general/misc.html#system-configuration

**Comment by maxrioux100** [comment]
I forgot to activate my environment for batches but even with those line and/or `source '/path/to/env/bin/activate'`

**Comment by kushalkolar** [comment]
Sorry about this, this seems to have been created by an update to the snap branch a few days ago. I just fixed it so if you run `git pull` in the `MESmerize` dir it should pull the fix and you should be able to run motion correction :)

**Comment by maxrioux100** [comment]
No problem, I test this out !

**Comment by maxrioux100** [comment]
I think this is working now. (I say think because the motion correction dont finish but I blame the computer I use because I see it compute and I see some console message) I will try to install linux on a computer that I already tested caiman successfully on it. thank you for your fast response.
