### ISSUE TITLE
CNMFE goes to orange

### ISSUE THREAD

**Issue by maxrioux100** [kushalkolar/MESmerize#16]
Hello, 
Still trying to figure out how to make mesmerize work.
Now when I run the CNMFE it always end up orange. From the logs, it look like it finished but its still not green.
I checked your documentation and orange means that the user aborted it but I didn't

![Screenshot from 2020-05-22 13-36-57](https://user-images.githubusercontent.com/40430512/82694804-ed7dda00-9c31-11ea-9f26-a41ba51c35c2.png)

**Comment by kushalkolar** [comment]
I think this is a bug when you have just one batch item. If you seen high CPU/RAM usage then CNMFE is occuring

**Comment by maxrioux100** [comment]
Where can I see the result?

**Comment by kushalkolar** [comment]
Double click the batch item

**Comment by maxrioux100** [comment]
Ok I ran it in a batches of 2 items, the first one resolved but now the cnmfe is red.
Here is the output.
![Screenshot from 2020-05-22 18-06-48](https://user-images.githubusercontent.com/40430512/82712945-59266e00-9c57-11ea-96c9-493320b11c13.png)

**Comment by kushalkolar** [comment]
Seems like it has something to do with your image data and/or parameters

**Comment by maxrioux100** [comment]
This is what I was thinking but I cant set the parameters exactly like on my test directly with caiman. K=none  or nb_patch=0(The interface doesnt allow me). Do you have any idea why some negative dimension would appear ?

**Comment by kushalkolar** [comment]
No idea sorry. The caiman supplied with mesmerize is a bit older, I'm currently working on updating mesmerize to be more up to date with caiman.

**Comment by maxrioux100** [comment]
Alright, is there a way to use the output from a more recent caiman and add them in Mesmerize for now ?

**Comment by kushalkolar** [comment]
Something like this in the viewer console might work if the CNMF data are still the same types of objects in newer versions of caiman:

```
get_module('roi_manager').start_cnmfe_mode()
get_module('roi_manager').manager.add_all_components(<args, kwargs>)
```


See http://mesmerizelab.org/api_reference/viewer_modules/roi_manager.html#mesmerize.viewer.modules.roi_manager_modules.managers.ManagerCNMFE.add_all_components

**Comment by maxrioux100** [comment]
Sorry for the delay, it was the weekend. Did you implement a way to do this directly with a .hdf5 file or do I need to code this function ? I'm asking since CaImAn output this info in those file and I think it could benefit from the users of your application.

**Comment by kushalkolar** [comment]
Yes I will try to have a way to import from Caiman hdf5 output files.

**Comment by kushalkolar** [comment]
@maxrioux100 This is now possible with mesmerize versions >= 0.2.0:
https://mesmerize.readthedocs.io/en/master/user_guides/viewer/modules/caiman_hdf5_importer.html

You can install it through pip:
https://github.com/kushalkolar/MESmerize#installation
