### ISSUE TITLE
Segmentation fault on macos when trying to start mesmerize

### ISSUE THREAD

**Issue by kitchell** [kushalkolar/MESmerize#26]
## Operating System
macOS catalina 10.15.7

## Details about your Mesmerize install
  - **Are you using the pip install? If so which version?**
  - **Are you using a clone of the master branch from the GitHub repo?**
  - **are you using anaconda or venv (the python built-in virtual environment management)** 

used pip install with anaconda env. followed the mac anaconda instruction directly: http://docs.mesmerizelab.org/en/master/user_guides/installation.html

## Describe the issue, please be as explicit and detailed as possible.

I have followed all the instructions for install, but when I start mesmerize it begins to open, then crashes and has a segmentation fault.

## Steps that can be followed to reproduce the problem. What exactly were you were doing that lead to the issue.
I created a new anaconda env and followed the install instructions. started mesmerize then it crashes.

## Screenshot or copy-paste from the terminal that Mesmerize is running in
**Make sure the entire stack trace is visible, or that all messages relevant to the issue are visible!**

(base) kitchlm1@C02CX47SMD6T-ML ~ % conda activate mesmerize
(mesmerize) kitchlm1@C02CX47SMD6T-ML ~ % mesmerize
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
objc[2335]: Class QMacAutoReleasePoolTracker is implemented in both /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x123213700) and /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x145ef11d0). One of the two will be used. Which one is undefined.
objc[2335]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x123213778) and /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x145ef1248). One of the two will be used. Which one is undefined.
objc[2335]: Class RunLoopModeTracker is implemented in both /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x1232137f0) and /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x145ef1270). One of the two will be used. Which one is undefined.
/Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
Loading, please wait... 
zsh: segmentation fault  mesmerize

## Anything else which you think is relevant

I have previously had mesmerize working on my laptop (though I remember having issues the first time installing, but different issues from the current one), but I recently tried to update caiman and mesmerize in the env. It worked, I thought ( I was able to open and use mesmerize), but a few days later when I tried to open it again, it would not work. I dont remember that error, but I removed the env and started from scratch. Now i cannot get mesmerize to open at all.

**Comment by kitchell** [comment]
I realized it might be linked to an issues with cv2. 

i was able to get the gui to open by doing 
``` 
pip uninstall opencv-python
pip uninstall opencv-contrib-python
```

and then reinstalling them as headless

```
pip install opencv-python-headless
pip install opencv-contrib-python-headless
```

I'm not sure if this will affect anything however.

**Comment by kushalkolar** [comment]
Hi,

Thanks for providing details!

I suspect that this might be a Qt related issue, what is your system Qt version? I think you can find this through:

`brew info qt5 | grep qt:`

And what is your `PyQt5` version within the environment:

``` python
from PyQt5 import QtCore
QtCore.PYQT_VERSION_STR
```

Installing headless `opencv` might have solved the issue since the headless packages doesn't include Qt, so the `opencv` in the environment was possibly making deprecated calls to the system Qt.

**Comment by kitchell** [comment]
Thanks for getting back to me!

for my mac I had to run 
``` qmake -v ```

```Using Qt version 5.9.7 in /Users/kitchlm1/opt/anaconda3/lib```

PyQt5 version is 5.12

I think this actually may be the same problem I had previously (though the errors are different I think) and I remember finding something about the issue being related to opencv being installed via conda and opencv-python and opencv-contrib-python being installed via pip, and thus this duplicate package issue happens:
```
Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/cv2/.dylibs/QtCore (0x123213778) and /Users/kitchlm1/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x145ef1248). One of the two will be used. Which one is undefined.
```
but that could have been a different problem with a different package (new computer, so I have been installing a lot of things lately)

**Comment by kushalkolar** [comment]
My guess is:
1. Qt shipped with opencv is conflicting with the Qt in the env libs.
2. The main Qt `5.9.7` libs are conflicting with the PyQt version which is newer

I would try:

Install opencv 4.2, 

``conda install -c conda-forge opencv==4.2.0``
^ not sure if that's the exact command, can't test since anaconda isn't working on my mac atm

If that doesn't fix the issue I'd also try:

Install a PyQt5 that's closer to the main libs in the env:
```
pip install PyQt5~=5.9.0
```

**Comment by kushalkolar** [comment]
I'm closing this since I guess you got it fixed, reopen if you have issues again.
