### ISSUE TITLE
Could not find Caiman

### ISSUE THREAD

**Issue by leironf** [kushalkolar/MESmerize#29]
## Details about your Mesmerize install
  - **Are you using the pip install? If so which version?** conda install -c conda-forge caiman
  - **Are you using a clone of the master branch from the GitHub repo?**
  - **are you using anaconda or venv (the python built-in virtual environment management)** 
I followed exactly what's here: http://docs.mesmerizelab.org/en/master/user_guides/installation.html#from-github-development

## Describe the issue, please be as explicit and detailed as possible.  Mesemerize starts but promts that caiman could not work since it is not in the environment but I can see is there
Also caimanmanager.py install didn't work: instead of running the command it prompted a how to open the .py

## Screenshot or copy-paste from the terminal that Mesmerize is running in
**Make sure the entire stack trace is visible, or that all messages relevant to the issue are visible!**

**Comment by leironf** [comment]
(mesmerize) PS C:\Users\ferrares> mesmerize
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\common\configuration.py:38: UserWarning: Caiman package not found. Caiman features will be disabled.
  "Caiman package not found. "
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
Loading, please wait...
===== 2020.11.18 21:11:25 =====
Traceback (most recent call last):
  File "c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\common\system_config_window.py", line 55, in set_ui_from_config
    n_threads = config['_MESMERIZE_N_THREADS']
TypeError: 'bool' object is not subscriptable
Work environment dumped!
===== 2020.11.18 21:11:00 =====
Traceback (most recent call last):
  File "c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\pyqtgraphCore\__init__.py", line 312, in cleanup
    if isinstance(o, QtGui.QGraphicsItem) and isQObjectAlive(o) and o.scene() is None:
ReferenceError: weakly-referenced object no longer exists
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\ferrares\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\pyqtgraphCore\__init__.py", line 312, in cleanup
    if isinstance(o, QtGui.QGraphicsItem) and isQObjectAlive(o) and o.scene() is None:
ReferenceError: weakly-referenced object no longer exists
(mesmerize) PS C:\Users\ferrares>

**Comment by kushalkolar** [comment]
Hi, thanks for posting an issue!

#. Are you sure that `caiman` is installed in the same environment as `mesmerize`? Can you `import caiman` from an ipython session?

#. I would not recommend installing `mesmerize` directly from the repo unless you want to modify/develop the code further.

#. Is there a specific reason you are using this within a VM? You will get better performance if you run it on bare metal.

**Comment by leironf** [comment]
Hi, thanks for replying.

1. I don't know: I did conda install -c conda-forge caiman with mesmerize active it did it smoothly and told me done at the end. inside anaconda mesmerize environment I can see the entry caiman. How can I import caiman from an ipython session?
2. Sorry I actually used this link http://docs.mesmerizelab.org/en/master/user_guides/installation.html#windows so the package not the repo
3. I have it also on a cluster but it's not interactive, I wanted it on the a VM with dedicated resources (it is powerful) so that I can find parameters interactively and then run the heavy part on the cluster.

**Comment by leironf** [comment]
I have restarted from scratch and found the problem, it was with pip installing mesmerize:
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

panel 0.10.2 requires bokeh>=2.2.2, but you'll have bokeh 2.1.1 which is incompatible.

Now mesmerize can see caiman

Thanks 
Best
Leiron

**Comment by kushalkolar** [comment]
Great to hear you got it working!
