### ISSUE TITLE
CalmAn features not enabled and working

### ISSUE THREAD

**Issue by akatav** [kushalkolar/MESmerize#31]
Hi,
I am on windows 10 with caiman installed as per instructions here: https://caiman.readthedocs.io/en/master/Installation.html#installation-on-macos-and-linux

I have followed instructions for installing mesmerize on windows. But while running `mesmerize`, the UI opens but CalmAn is not working. 
![image](https://user-images.githubusercontent.com/721570/100495405-d5fa4d80-318e-11eb-97e3-4076ed1b1dc9.png)

I checked ../mesmerize/lib/site-packages/ and caiman is installed correctly. Any pointers to resolve this will be helpful. 
![image](https://user-images.githubusercontent.com/721570/100495437-3b4e3e80-318f-11eb-9df6-f221ad750afc.png)

**Comment by kushalkolar** [comment]
Can you go into an ``ipython`` shell in the ``mesmerize`` environment and see if you can ``import caiman``

**Comment by akatav** [comment]
@kushalkolar  yes,i can. 
![image](https://user-images.githubusercontent.com/721570/100496462-997f1f80-3197-11eb-8939-f04c6e88defc.png)

although i did resolve an error earlier with oasis import before this import inside ipython could work.

**Comment by kushalkolar** [comment]
alright, are you able to launch ``memerize`` and not get the warning about ``caiman`` now?

**Comment by akatav** [comment]
@kushalkolar actually,  that was my initial issue as well.I could `import caiman` inside ipython within the mesmerize env.But outside of ipython, when i ran `'memerize`, the mesmerize GUI opened up well but the warning about `caiman` did not go away.

**Comment by kushalkolar** [comment]
Strange, are you able to ``import caiman`` in the mesmerize console in the [welcome window](http://docs.mesmerizelab.org/en/master/user_guides/general/misc.html)

**Comment by akatav** [comment]
@kushalkolar thank you. actually, i could do `'import caiman` inside the mesmerize console but on some other modules inside `source_extraction`, the `oasis` package not found error occurred. 
Turned out i needed to do `python setup.py build_ext -i` command again. Now i am not getting the `caiman not found` on `mesmerize` startup.

**Comment by kushalkolar** [comment]
can you make a clean environment? If you're using caiman on windows I think it's best to just use the conda package due to installation difficulties on Windows.

**Comment by kushalkolar** [comment]
Follow this for Windows:
http://docs.mesmerizelab.org/en/master/user_guides/installation.html#windows

**Comment by akatav** [comment]
@kushalkolar actually, i followed the above link for installation of mesmerize on windows. but i had already installed caiman and was working on it in a separate virtual env, i installed `caiman` inside mesmerize env again. 
I do not get the warning about `caiman` anymore inside `mesmerize`.

**Comment by kushalkolar** [comment]
python (and mesmerize is a python application) will only be able to import packages that are in the current environment

if this helps, here's an explanation of virtual environments: https://realpython.com/python-virtual-environments-a-primer/#:~:text=Remove%20ads-,What%20Is%20a%20Virtual%20Environment%3F,dependencies%20every%20other%20project%20has.

So I guess I can mark this as resolved then?

**Comment by akatav** [comment]
@kushalkolar yes, resolved. thanks.
