### ISSUE TITLE
Ease installation

### ISSUE THREAD

**Issue by clbarnes** [kushalkolar/MESmerize#32]
The installation process is a little tricky; I wonder if it could be made easier with:

1. [PEP-518](https://www.python.org/dev/peps/pep-0518/) build-time dependency specification for minimum versions of numpy, cython, setuptools
2. CaImAn, tensorflow, tslearn, bottleneck etc as a [optional features](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies)
3. Pip installing CaImAn directly from github without having to clone separately (preferably with a tag specifier): `pip install git+https://github.com/flatironinstitute/CaImAn.git@v1.8.6`

This should reduce 6 steps in the installation (linux, at least) down to 1. If the installation procedure (once a python environment is set up) can be brought down to a single invocation of pip, matters could be simplified even further by recommending the use of [pipx](https://github.com/pipxproject/pipx), which would manage the virtual environment and linking onto the path as well, although then the python version limitation may be more problematic.

No worries if these options have been considered and discounted in the past, though! It looks like it's even more tricky on different platforms, which may make these changes not possible.

**Comment by kushalkolar** [comment]
Thanks for your suggestions!

1 & 2: Yup I've tried this but I think the issue was that pip does not resolve build-time dependencies recursively and creates issues when installing tslearn which also has build time dependencies

3: Thanks, I'll see if this works!

**Comment by clbarnes** [comment]
> I think the issue was that pip does not resolve build-time dependencies recursively and creates issues when installing tslearn which also has build time dependencies

Ah yes, looks like the current version of tslearn has its own pyproject.toml so this may handle itself in the future, but the version mesmerize depends on does not.

**Comment by kushalkolar** [comment]
The version of ``tslearn`` (latest pypi release) that ``mesmerize`` works with does have a ``pyproject.toml``. When I tried incorporating a ``pyproject.toml`` for ``mesmerize`` it did not work properly due to the ``tslearn`` one.

**Comment by clbarnes** [comment]
It seems I was looking at the pinned version in `requirements.txt`, which is 0.2.2 and doesn't have a `pyproject.toml`; good to know more recent versions are supported though. Weird that pip doesn't do PEP 518 with the deps, its support for it has been lagging a bit.

**Comment by clbarnes** [comment]
I went a couple of layers deep into this.

For information purposes, `tslearn` specifies its build deps but doesn't explicitly tell them to use a particular build system. It gets a bit further with that change, but then falls apart when it tries to install numba. Numba is also not 518-compliant; I tried converting it, which required the use of the non-vendored form of `versioneer`. That seems to cause some problems with resolving the path to `setup.cfg`.

**Comment by kushalkolar** [comment]
Yea I spent quite a while trying to figure it out. I may try to create a snap install again (or use another container system) in the future to make a 1 liner install.

**Comment by clbarnes** [comment]
[Ilastik](https://www.ilastik.org/) manages to bundle a whole conda environment together into their binary; I think using [this repo](https://github.com/ilastik/ilastik-install), but it seems like a bit of a pig to maintain.

**Comment by kushalkolar** [comment]
Yea, similarly snap packages all system libs and and an entire Python environment into a container. But also very tedious to maintain.
