### ISSUE TITLE
Install caiman for Caiman feature failed on Mac

### ISSUE THREAD

**Issue by nrandel** [kushalkolar/MESmerize#33]
## Operating System & specs (CPU, RAM etc.)
MacOS 10.14.6
2.9GHz Intel Core i9
Processor Speed:	2.9 GHz 
Number of Processors:	1
Total Number of Cores:	6
Memory 32GB

## Details about your Mesmerize install
  - **Are you using the pip install? If so which version?**
pip 19.1.1 from /Users/nadine/anaconda3/lib/python3.7/site-packages/pip (python 3.7)

  - **Are you using a clone of the master branch from the GitHub repo?**
following the installation.doc for MacOs send via email
  - **Are you using anaconda or venv (the python built-in virtual environment management)** 
anaconda

## Describe the issue, please be as explicit and detailed as possible.
- conda activate mesmerise (works)
- next step: it freezes dor >1h
see output below:
conda install -c conda-forge caiman
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 

## Screenshot or copy-paste from the terminal that Mesmerize is running in
**Make sure the entire stack trace is visible, or that all messages relevant to the issue are visible!**

Last login: Sat Nov 28 10:51:45 on ttys000
(base) Nadines-MacBook-Pro:~ nadine$ conda activate mesmerize
(mesmerize) Nadines-MacBook-Pro:~ nadine$ conda install -c conda-forge caiman
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -

**Comment by kushalkolar** [comment]
Thanks for providing details!

What's the conda version number?

Can you try this in the ``mesmerize`` environment:

```
conda config --remove channels conda-forge
conda config --add channels conda-forge
```

**Comment by nrandel** [comment]
Thank you for the reply!

conda 4.7.10

I try what you suggested and paste below the terminal entry: 

I was not sure if 

'''conda install -c conda-forge caiman''' 

was needed afterwards.


(base) Nadines-MacBook-Pro:~ nadine$ conda activate mesmerize
(mesmerize) Nadines-MacBook-Pro:~ nadine$ conda config --remove channels conda-forge

CondaKeyError: 'channels': 'conda-forge' is not in the 'channels' key of the config file

(mesmerize) Nadines-MacBook-Pro:~ nadine$ conda config --add channels conda-forge
(mesmerize) Nadines-MacBook-Pro:~ nadine$ conda config --remove channels conda-forge
(mesmerize) Nadines-MacBook-Pro:~ nadine$ conda config --add channels conda-forge
(mesmerize) Nadines-MacBook-Pro:~ nadine$ conda install -c conda-forge caiman
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -

**Comment by kushalkolar** [comment]
Just looked at your first message again and I think you might be using a ``pythoon 3.7`` environment. Can you make a clean environment with ``3.6``:

```
conda create --name mesmerize python=3.6
```

**Comment by nrandel** [comment]
Thank you very much! This was indeed the problem. The rest of the installation went smoothly.

Looking forward to the workshop!

**Comment by kushalkolar** [comment]
Glad to hear it worked! When you launch ``mesmerize`` can you make sure you don't get a message stating that caiman cannot be found?

**Comment by LBezaresCalderon** [comment]
Hi,
 same issue here, but removing/adding conda-forge channel didn't solve the issue for me. I installed python 3.6 in the mesmerize env. 
May it be that I have to downgrade my Conda version (I currently have conda 4.9.2)? Thanks

**Comment by kushalkolar** [comment]
@LBezaresCalderon did you explicitly create the conda environment with 3.6:

```
conda create --name mesmerize python=3.6
```

**Comment by LBezaresCalderon** [comment]
yes

**Comment by kushalkolar** [comment]
You could try downgrading your anaconda, but can you copy-paste everything from the terminal to make sure there isn't something else.

**Comment by LBezaresCalderon** [comment]
Ok, thanks @kushalkolar.

This is what ran in my terminal after creating the environment with

 `conda create --name mesmerize python=3.6`


## Package Plan ##

  environment location: /anaconda3/envs/mesmerize

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.11.8          |   py36h79c6626_0         150 KB  conda-forge
    libffi-3.3                 |       h74dc148_1          45 KB  conda-forge
    ncurses-6.2                |       h2e338ed_4         881 KB  conda-forge
    openssl-1.1.1h             |       haf1e3a3_0         1.9 MB  conda-forge
    pip-20.2.4                 |             py_0         1.1 MB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    readline-8.0               |       h0678c8f_2         255 KB  conda-forge
    sqlite-3.33.0              |       h960bd1c_1         1.7 MB  conda-forge
    tk-8.6.10                  |       hb0a8c7a_1         3.3 MB  conda-forge
    xz-5.2.5                   |       haf1e3a3_1         228 KB  conda-forge
    zlib-1.2.11                |    h7795811_1010         102 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         9.5 MB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2020.11.8-h033912b_0
  certifi            conda-forge/osx-64::certifi-2020.11.8-py36h79c6626_0
  libcxx             conda-forge/osx-64::libcxx-11.0.0-h4c3b8ed_1
  libffi             conda-forge/osx-64::libffi-3.3-h74dc148_1
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  openssl            conda-forge/osx-64::openssl-1.1.1h-haf1e3a3_0
  pip                conda-forge/noarch::pip-20.2.4-py_0
  python             pkgs/main/osx-64::python-3.6.12-h26836e1_2
  python_abi         conda-forge/osx-64::python_abi-3.6-1_cp36m
  readline           conda-forge/osx-64::readline-8.0-h0678c8f_2
  setuptools         pkgs/main/osx-64::setuptools-50.3.1-py36hecd8cb5_1
  sqlite             conda-forge/osx-64::sqlite-3.33.0-h960bd1c_1
  tk                 conda-forge/osx-64::tk-8.6.10-hb0a8c7a_1
  wheel              conda-forge/noarch::wheel-0.35.1-pyh9f0ad1d_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010


Proceed ([y]/n)? y


Downloading and Extracting Packages
xz-5.2.5             | 228 KB    | ##################################### | 100% 
openssl-1.1.1h       | 1.9 MB    | ##################################### | 100% 
python_abi-3.6       | 4 KB      | ##################################### | 100% 
zlib-1.2.11          | 102 KB    | ##################################### | 100% 
sqlite-3.33.0        | 1.7 MB    | ##################################### | 100% 
libffi-3.3           | 45 KB     | ##################################### | 100% 
pip-20.2.4           | 1.1 MB    | ##################################### | 100% 
tk-8.6.10            | 3.3 MB    | ##################################### | 100% 
ncurses-6.2          | 881 KB    | ##################################### | 100% 
readline-8.0         | 255 KB    | ##################################### | 100% 
certifi-2020.11.8    | 150 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mesmerize
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) bezares-nb-4:~ LuisBezares$ source activate mesmerize
(mesmerize) bezares-nb-4:~ LuisBezares$ conda config --remove channels conda-forge
(mesmerize) bezares-nb-4:~ LuisBezares$ conda config --add channels conda-forge
(mesmerize) bezares-nb-4:~ LuisBezares$ conda install -c conda-forge caiman
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \- \ failed with initial frozen solve. Retrying with flexible solve.

**Comment by kushalkolar** [comment]
Is this a new installation of anaconda or have you had it for other things for a long time?

```
conda clean --all
```

**Comment by atheneknufer** [comment]
Hi there, I've been having the same issue as above, have created the conda environment with python 3.6, get stuck in the same place and tried all the above suggestions. tried a fresh install of anaconda with an earlier version and this is what i get now, it's been stuck on 'solving environment' for some time.

(base) Athenes-MacBook-Pro-2:~ clarkelab$ conda update -n base -c defaults conda
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/clarkelab/anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py37hecd8cb5_0         3.1 MB
    conda-package-handling-1.7.2|   py37h22f3db7_0         1.6 MB
    ------------------------------------------------------------
                                           Total:         4.7 MB

The following NEW packages will be INSTALLED:

  conda-package-han~ pkgs/main/osx-64::conda-package-handling-1.7.2-py37h22f3db7_0

The following packages will be UPDATED:

  conda                                       4.6.11-py37_0 --> 4.9.2-py37hecd8cb5_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.9.2          | 3.1 MB    | ##################################### | 100% 
conda-package-handli | 1.6 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) Athenes-MacBook-Pro-2:~ clarkelab$ conda create --name mesmerize python=3.6

## Package Plan ##

  environment location: /Users/clarkelab/anaconda3/envs/mesmerize

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2020.10.14-0
  certifi            pkgs/main/osx-64::certifi-2020.11.8-py36hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libedit            pkgs/main/osx-64::libedit-3.1.20191231-h1de35cc_1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1h-haf1e3a3_0
  pip                pkgs/main/osx-64::pip-20.2.4-py36hecd8cb5_0
  python             pkgs/main/osx-64::python-3.6.12-h26836e1_2
  readline           pkgs/main/osx-64::readline-8.0-h1de35cc_0
  setuptools         pkgs/main/osx-64::setuptools-50.3.1-py36hecd8cb5_1
  sqlite             pkgs/main/osx-64::sqlite-3.33.0-hffcf06c_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  wheel              pkgs/main/noarch::wheel-0.35.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mesmerize
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) Athenes-MacBook-Pro-2:~ clarkelab$ conda activate mesmerize
(mesmerize) Athenes-MacBook-Pro-2:~ clarkelab$ conda install -c conda-forge caiman
Collecting package metadata (repodata.json): done
Solving environment: -

**Comment by kushalkolar** [comment]
@atheneknufer 
Thanks for the details. Unfortunately this problem of conda hanging on 'solving environment' is quite common :( .It's partly why I no longer use conda for my own work. Right now I'd just leave it as is and see if it finishes by the morning.

**Comment by atheneknufer** [comment]
@kushalkolar thanks, that's good to know. I guess it's better than my first try, at least it hasn't failed yet....

**Comment by kushalkolar** [comment]
I'm going to close this for now and see if I can figure out how to get it installed on mac using just virtual environments in a few days.

**Comment by ASiliciano** [comment]
Would desperately appreciate a fix for this as well.  I've been stuck at `Solving environment:` for several hours.  Thanks!
