### ISSUE TITLE
Using mesmerize to select cells by tuning Caiman Quality parameters

### ISSUE THREAD

**Issue by akatav** [kushalkolar/MESmerize#36]
With your help, I have successfully installed `mesmerize` and got `caiman` working in Windows 10. 

I have already used caiman to correct for motion and detect cells from in vivo Calcium imaging datasets. I am trying to select good quality cells using the quality params of caiman. As the data is processed already as mentioned, i have the .mmap files, the `corr` and `pnr` files alongwith the `cnm_estimates` object saved as well. 

I'd like to know how to use `mesmerize` to interactively tuning all  quality params simultaneously (using sliders for instance) (rval_thr, use_cnn, min_snr etc) so that i can minimize false positives and also select all good quality cells (that are visually well defined, visible to the eye)

![set4-1X0](https://user-images.githubusercontent.com/721570/100706540-89ac4900-33ec-11eb-8715-bfb5303159fb.jpg)

for example, in the above image, some cells are missed, many overlap. 

Can you please tell me how to do this using mesmerize with the mmap file and cnm_Estimate obj?

**Comment by kushalkolar** [comment]
Have you created CNMFE batch items using mesmerize or are these caiman outputs from your own notebook/script?

If you want to tune `corr_pnr` and `min_pnr` for CNMFE, you have to do it with the caiman modules built in to mesmerize using the batch manager:
http://docs.mesmerizelab.org/en/master/user_guides/viewer/modules/cnmfe.html

**Comment by akatav** [comment]
thank you for replying. actually, that img from my caiman notebook. I have already tuned corr_pnr and min_pnr. 
As you can see in that img, some cells are missed and some cells overlap even after the quality param tuning (see under: https://caiman.readthedocs.io/en/master/Getting_Started.html#component-evaluation). Right now, i am just changing these params by hand everytime and running the scripts repetitively to select the right number of components using `evaluate_components` method in caiman as follows:

`Yr, dims, T = cm.load_memmap('msCam1_memmap__d1_480_d2_752_d3_1_order_C_frames_17967_.mmap')
images = Yr.T.reshape((T,) + dims, order='F')
cnm.params.set('quality',{'SNR_lowest': 1,
 'min_SNR': 9,
 'gSig_range':[3,8],
 'rval_lowest': -1,
 'rval_thr': 3,
 'use_cnn': True,
 'min_cnn_thr': 0.9,
 'cnn_lowest':0.1});
cnm.estimates.evaluate_components(images, cnm.params, dview=dview)
`
I am looking to see if `mesmerize` has any interactive gui to change these quality params (using say like a slider  feature) and select good quality cells.

**Comment by kushalkolar** [comment]
The docs and video tutorials cover what's available for this
