### ISSUE TITLE
Still struggling with Caiman installation with Windows 10

### ISSUE THREAD

**Issue by mirandarobbins** [kushalkolar/MESmerize#38]
I have a folder in Users that is CalmAn but the conda install -c conda-forge caiman step starts but then seems to stall half way through. I have increased the maximum size of my pagefile, could the issue be I need to increase it more? There are no errors just failure to complete after running for a very long time...

Thanks,

**Comment by kushalkolar** [comment]
Can you copy-paste from the powershell so I can see exactly what you did?

Did you start from a fresh new environment for python3.6?

**Comment by mirandarobbins** [comment]
![image](https://user-images.githubusercontent.com/9307589/100806648-bda55f80-3428-11eb-8eb9-8bd9b604984f.png)

I used python 3.6 this time, here's where it stalls

**Comment by kushalkolar** [comment]
can you delete the environment that already exists and then try to install caiman in a new fresh python3.6 environment

**Comment by mirandarobbins** [comment]
![image](https://user-images.githubusercontent.com/9307589/100863275-3be71d80-348c-11eb-8df9-9a359378e1a9.png)



Hi Kushal, still stalls here. I'll just observe for the workshop as perhaps my laptop just isn't up to it. 
Thanks,
-Miranda

**Comment by kushalkolar** [comment]
@mirandarobbins did this work with:
```
conda install -c conda-forge caiman==1.8.5
```

Thanks for attending!

**Comment by mirandarobbins** [comment]
Hi Kushal, 
Unfortunately not. Thanks for the workshop though, hopefully I can try from a better computer sometime!

**Comment by kushalkolar** [comment]
Not sure what causes the solving environment to hang, it might be insufficient system resources. I just did a fresh install on a new Windows 10 installation and it only took a few seconds. You might get some help by posting an issue on the Caiman github page since the first step to installing `mesmerize` is to install `caiman` through their conda package.
