### ISSUE TITLE
ModuleNotFoundError: No module named 'caiman'

### ISSUE THREAD

**Issue by kevinpan0127** [kushalkolar/MESmerize#47]
## Operating System & specs (CPU, RAM etc.)
Windows, Intel Core i7, 16GB RAM

## Details about your Mesmerize install
Followed installation on the mesmerize document page for windows.

## Describe the issue, please be as explicit and detailed as possible.
I am trying to run motion correction with my own data. I am following the video tutorial but when I start to run the batch for motion correction, I get the following error:

File "c:\users\panyi\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\batch_run_modules\caiman_motion_correction.py", line 23, in
import caiman as cm
ModuleNotFoundError: No module named 'caiman'

Is there a way to solve this issue?
I have successfully installed the caiman manager using "caimanmanager.py install", but the caiman_data file is showing under the path "C:\Users\panyi". Is this an issue?

**Comment by kushalkolar** [comment]
What happens when you run ``import caiman`` in ``ipython`` ?

What do your system configuration settings look like (screenshot) , see the note in the blue box at the end of the installation steps: http://docs.mesmerizelab.org/en/master/user_guides/installation.html#windows

**Comment by kevinpan0127** [comment]
Thank you for the quick reply! I have uncommented the # conda activate mesmerize and it now works!

**Comment by kushalkolar** [comment]
glad that it works!
