### ISSUE TITLE
RuntimeError Using CNMF Module

### ISSUE THREAD

**Issue by kevinpan0127** [kushalkolar/MESmerize#48]
I am running the CNMF module on motion corrected tiff image. I am getting a runtime error. Below is entire traceback, thank you very much!

C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\panyi\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\batch_run_modules\CNMF.py", line 34, in <module>
    from mesmerize.common.utils import HdfTools
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\__init__.py", line 1, in <module>
    from .analysis import *
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\analysis\__init__.py", line 3, in <module>
    from .math import cross_correlation, drfft_dtw, tvregdiff
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\analysis\math\drfft_dtw.py", line 17, in <module>
    raw_curve: np.ndarray = None, rf_curve: np.ndarray = None) -> list:
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\managers.py", line 513, in start
    self._process.start()
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\panyi\anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
===== 2020.12.28 21:12:31 =====

**Comment by kushalkolar** [comment]
@kevinpan0127 Thanks for posting the issue, I'll try to fix this within a few days.

**Comment by kevinpan0127** [comment]
Hi @kushalkolar!
I  was wondering if there is any update on solving this issue? Thank you very much for your time!

**Comment by neurowookie** [comment]
Hi @kushalkolar , 
I'm having the same issue. Any luck in fixing it?

**Comment by kushalkolar** [comment]
@kevinpan0127 @neurowookie sorry for the delay, I didn't have access to a windows machine for testing. Fixed in master, will make a new release soon :)

**Comment by kushalkolar** [comment]
now fixed in the v0.5.0 release.
