### ISSUE TITLE
[BUG] ROIs in HDF5 file are not matching with their respective traces correctly 

### ISSUE THREAD

**Issue by Bilalgp** [kushalkolar/MESmerize#50]
**Describe the bug**
If you were to create an HDF5 file from caiman commands in a jupyter notebook and load the the hdf5 file ROIs in mesmerize, there is a problem.

The traces load properly, and the ROI map loads properly. However, the traces do not correctly associate with the ROI. Below is an example. In the notebook, the trace is associated with an ROI (may be hard to see but it's a shadow overlay on the middle-left of the Bokeh figure. However, in mesmerize the same trace is associated with a different ROI. 

I can share files associated with the photo privately if that works. 

![image](https://user-images.githubusercontent.com/26805330/109432132-c54cb400-79d7-11eb-827b-3edee2796aae.png)

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - OS: Windows 10, 64 GB RAM, i7, GTX 3070 

**Details about your Mesmerize install**
  - anaconda prompt installed mesmerize

**Comment by kushalkolar** [comment]
Thanks for the details, you can share the file through gitter.

Was the imported file created from a session after component selection and/or selection using caiman's GUI (their GUI for component selection, not mesmerize's).

**Comment by Bilalgp** [comment]
Thanks for the prompt response.

The imported hdf5 file was created from the caiman demo pipeline where we use the cnm.save() function. I've been having trouble using the Caiman GUI so I was using mesmerize. 

Which file do you think you would need for this? Is the hdf5 file sufficient?

**Comment by kushalkolar** [comment]
fixed in master, will be available in next release (in a few hours)

![image](https://user-images.githubusercontent.com/9403332/109477427-4bb8d280-7a78-11eb-87e6-1c23f5a6762b.png)
![image](https://user-images.githubusercontent.com/9403332/109478921-1e6d2400-7a7a-11eb-9b1e-8ab45da7c7d1.png)

**Comment by kushalkolar** [comment]
v0.5.1 is out on pypi

**Comment by Bilalgp** [comment]
Thank you!
