### ISSUE TITLE
[BUG] System configuration setting yields an error

### ISSUE THREAD

**Issue by EricThomson** [kushalkolar/MESmerize#53]
**Describe the bug**
When I try to set system configuration (clicking apply in the gui)  I get an Insufficient Permissions error popup. I'm running from powershell in admin mode in Windows 10.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to Configuration --> System Configuration
2. Click Apply (it doesn't matter what I do, change number of processes, or nothing, just click apply)

**Copy paste message from the error window (if any)**
INsufficient permissions. You do not have write access to the chosen work directory.

![image](https://user-images.githubusercontent.com/6643322/119005489-7c185a80-b95d-11eb-9cb8-99bb5f504e94.png)

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - OS: [e.g. Windows 10, Mac OSX Mojave 10.14, Ubuntu 20.04 LTS]
Windows 10, 128 GB Ram, Intel Xeon CPU

**Details about your Mesmerize install**
I used mamba to install caiman, pip to install mesmerize.

**Comment by EricThomson** [comment]
Thanks -- that worked. I thought of doing that but thought it would yield the same error.  :)

**Comment by kushalkolar** [comment]
Good to know, thanks! I'm not a fan of `conda` because of issues like this, I'll check out `mamba` for other users. I prefer just using plain python virtual environments.
