### ISSUE TITLE
Problem Exporting Video

### ISSUE THREAD

**Issue by katherinekelly2012** [kushalkolar/MESmerize#57]
**Describe the bug**

When I attempt to export my video I get the pop up form, but when I press the second export I get the following error:

AssertionError: Unknown encoder extension

**To Reproduce**

1. Go to viewer
2. Click on image then load image 
3. Press on export button above histogram
4. With the form, press export again
5. Then the error occurs

**Expected behavior**
I expected it to export

**Copy paste message from the error window (if any)**

This is the error from the 'Show Details':

Traceback (most recent call last):
  File "c:\users\katherine\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\common\qdialogs.py", line 52, in fn
    return func(self, *args, **kwargs)
  File "c:\users\katherine\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\exporter.py", line 111, in export
    writer = skvideo.io.FFmpegWriter(f'{path}.{extn}', outputdict=output_params)
  File "c:\users\katherine\miniconda3\envs\mesmerize\lib\site-packages\skvideo\io\ffmpeg.py", line 336, in __init__
    assert str.encode(self.extension).lower() in _FFMPEG_SUPPORTED_ENCODERS, "Unknown encoder extension: " + self.extension.lower()
AssertionError: Unknown encoder extension: 

**Copy-paste or take a screenshot of the terminal that Mesmerize is running in**
```
![image](<img width="960" alt="terminalfromerror" src="https://user-images.githubusercontent.com/77304549/123695196-430aba00-d828-11eb-8577-a0fd82625234.png">

```
_Make sure the entire stack trace is visible, and all messages relevant to the issue are visible._

**If relevant, messages from the batch manager terminal**

**Screenshots**
<img width="717" alt="errorimage" src="https://user-images.githubusercontent.com/77304549/123695352-71889500-d828-11eb-9340-cb7f83334e21.png">

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - OS: Windows 10
 - 
**Details about your Mesmerize install**
  - anaconda
  - pip 21.1.2

**Comment by kushalkolar** [comment]
Hi, @katherinekelly2012 

Thanks for providing details!

You haven't entered a path to export it, enter a path or click the `...` button to choose a path for the exported file. I think that both `.mp4` and `.avi` extensions will work for `x264`. I'm sorry that this module isn't documented, I'll try to add it to the docs this week.

Let me know if it works for you!
