### ISSUE TITLE
ModuleNotFoundError: No module named 'caiman'

### ISSUE THREAD

**Issue by katherinekelly2012** [kushalkolar/MESmerize#58]
There seem to be similar problems, but the solutions do not seem to be working. I am trying to do motion correction and then CNMF. When I do the motion correction and I originally received the "No module name 'cv2'" and I got that fixed by reinstalling the package. But now I am getting the "ModuleNotFoundError: No module named 'caiman'". I tried reloading caiman and it did not change the error even after I restarted the program. 

**To Reproduce**
1. Go to CaImAn toolbox and choose motion correct
2. Put in parameters and add it to the batch
3. Run the batch

Traceback (most recent call last):
  File "c:\users\katherine\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\batch_run_modules\caiman_motion_correction.py", line 23, in <module>

    import caiman as cm
ModuleNotFoundError: No module named 'caiman'

Traceback (most recent call last):
  File "c:\users\katherine\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\batch_run_modules\caiman_motion_correction.py", line 23, in <module>

    import caiman as cm
ModuleNotFoundError: No module named 'caiman'

Traceback (most recent call last):
  File "c:\users\katherine\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\batch_run_modules\caiman_motion_correction.py", line 23, in <module>

    import caiman as cm
ModuleNotFoundError: No module named 'caiman'

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - OS: Windows 10

**Details about your Mesmerize install**
  - Anaconda

**Comment by kushalkolar** [comment]
@katherinekelly2012 Thanks for providing all the details!

What does your System Configuration look like? You can access it from the Welcome Window, go to Configuration -> System Configuration:
![image](https://user-images.githubusercontent.com/9403332/124158055-c0893100-da99-11eb-876a-6e5de1ba8d6e.png)

You have to make sure that the conda activation command is added the big text box:
http://docs.mesmerizelab.org/en/master/user_guides/general/misc.html#system-configuration

**Comment by katherinekelly2012** [comment]
<img width="373" alt="configruation" src="https://user-images.githubusercontent.com/77304549/124158720-3eccdf80-da68-11eb-863e-5eea4a241907.PNG">

**Comment by katherinekelly2012** [comment]
Is this where I need to remove the # from conda activate mesmerize?

**Comment by kushalkolar** [comment]
Yup!

**Comment by katherinekelly2012** [comment]
Thanks!
