### ISSUE TITLE
[BUG] correlation_pnr() output has edge artifacts not present when I run same in caiman

### ISSUE THREAD

**Issue by EricThomson** [kushalkolar/MESmerize#62]
**Describe the bug**
When I run the "inspect correlation and pnr" step of cnmfe and look at the image, there are very large edge artifacts in both the correlation image and pnr image that are not present when I run the same method in caiman. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to Caiman toolbox and select CNMF-E and enter gSig value (say, 7) and add to batch.
2. Run the batch and then inspect the result.
3. Anomalous image pops up.

**Expected behavior**
Should look the same in both caiman and mesmerize.

**Screenshots**
From caiman:
![pnr_gsig7_caiman](https://user-images.githubusercontent.com/6643322/128107865-fd8e3a95-3357-4ed4-b661-9707f74fd859.png)

From mesmerize (note the bright artifact band around the outer edge of the image for both corr and pnr):
![pnr_gsig7](https://user-images.githubusercontent.com/6643322/128107895-4609ea88-c39d-4b1b-92c8-6ccde5e2b7b0.png)

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
Windows 10 128GB RAM Xeon Processor (2.4GHz)

**Details about your Mesmerize install**
Mesmerize 0.7.1 installed using pip.

**Additional comments**
I poked around in the source code:
https://github.com/kushalkolar/MESmerize/blob/0b884e758a9fca2dac3e9106721ece5c0daf9f28/mesmerize/viewer/modules/batch_run_modules/CNMFE.py#L117

I can't see anything strange going on it is running the exact same method as the caiman code. This is truly a head-scratcher. I have seen since I started using mesmerize though so I know it's not just a one-off thing. I haven't dug very deeply into it would be nice to know if others see the same thing.

**Comment by kushalkolar** [comment]
Thanks for the details @EricThomson !

Are you setting your border pixel parameters when you run it yourself in a notebook?

**Comment by kushalkolar** [comment]
This looks like it's either due to border pixel not being set in your notebook, or the nan border not being set in mesmerize for some reason.

**Comment by EricThomson** [comment]
Good point I did not mess with that, and that's almost certainly the culprit. I was a little confused about how to set it as a kwarg because with the "stop here" option it seemed there is only the `gSig` parameter to tweak I assumed the kwarg window was only for when you go full CNMFE. 

When I try to change params in the kwarg window (e.g., with `bord_px=0` or `border_nan='copy'` or `border_pix=0`) the `border_pix` parameter stays 12 so I am getting the same result.

**Comment by kushalkolar** [comment]
Are you setting the bord pix when running it in a notebook though?
Mesmerize should set it automatically.

**Comment by EricThomson** [comment]
Yes I'm setting it to 0, and using `border_nan='copy'` this is what I was trying to recreate with kwargs.

**Comment by EricThomson** [comment]
Yes as I mentioned when I manually set `bord_px` to 12 in my notebook (the same value it is being set to in mesmerize), I get the artifact so that is the issue.

**Comment by kushalkolar** [comment]
Ah ok! In your notebook if you don't set border pix does CNMF pick up junk in the border area?

**Comment by EricThomson** [comment]
I think maybe just adding a border_pix  option for this method would help. When I set `bord_px` in the kwarg window for cnmfe it seems to work.  

For now I'm just zeroing it out in cnmfe.py around line 49 where it pulls it from the motion correction outputs, and it seems to be working fine.

**Comment by kushalkolar** [comment]
@EricThomson So if I understand correctly, if there's a checkbox for `border_nan='copy'` which sets that kwarg and simultaneously doesn't pass the `bord_px` at all that would solve the issue? If so I could show you how to add this to GUI, takes 5 mins :D.

**Comment by kushalkolar** [comment]
You'll just need to install `qtcreator`, not sure how to do that on Windows though.

**Comment by EricThomson** [comment]
I think _something_ like that would be good. Yes it would be great for me to start to learn to make these adjustments. I have a Linux machine with Qt Creator set up it might be better to do dev work there. Let me work on setting up a caiman/mesmerize environment on that machine this weekend, and getting Qt Creator resuscitated. I think maybe fewer headaches if I just do it on Ubuntu probably.

**Comment by kushalkolar** [comment]
@EricThomson Do you want to make a PR for this sometime?

**Comment by EricThomson** [comment]
Yes that would probably be helpful. I can do a quick one soon (probably next weekend I'm about to get slammed this week in lab stuff).
