### ISSUE TITLE
CaImAn instalattion error

### ISSUE THREAD

**Issue by szocs93** [kushalkolar/MESmerize#66]
Dear all!

I'm trying to install mesmerize on Windows and been stuck with installation. (see attached image) I've been waiting more than 28 hours and still not doing anything and not moving forward. I tried a few commands for caiman install and both ended up here.
Someone has some idea how to solve it?

Thanks in advance,
Szilárd
![crop](https://user-images.githubusercontent.com/43432370/136160043-96d71f00-bde9-4879-908b-d3caf5230c41.JPG)

**Comment by mestmas** [comment]
Hi!!
One of the issues could be missing visual studio (required for caiman installation):
" Install Microsoft Build Tools for Visual Studio 2017 https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017. You can find older versions of visual studio in a link to older tools at the bottom of the page. Check the “Build Tools” box, and in the detailed view on the right check the “C/C++ CLI Tools” component too. The specifics of this occasionally change as Microsoft changes its products and website; you may need to go off-script"

if still not working try to clone and installing it from github directly (it did work for me):
- Clone CaImAn
git clone https://github.com/flatironinstitute/CaImAn  (you can clone wherever you want)

- cd into the folder in which you cloned CaImAn
- activate mesmerize enviroment
- install CaImAn:
pip install . 

Hope it helps.

**Comment by kushalkolar** [comment]
@szocs93 https://github.com/flatironinstitute/CaImAn/issues/924

**Comment by kushalkolar** [comment]
@szocs93 please look into the mamba installation for caiman
