### ISSUE TITLE
[BUG Daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by mestmas** [kushalkolar/MESmerize#67]
Hi all, 

**Describe the bug**
I'm trying to run  "extractstim" from flowchart and I always get the program bolcked and the error: Daemonic processes are not allowed to have children. 

**To Reproduce**
Steps to reproduce the behavior, for example:
![image](https://user-images.githubusercontent.com/92024598/136252052-50a55df6-5b7d-4af4-929d-58bae612f789.png)

**Expected behavior**
Extract portions of curves according to stimulus mpas

**Copy paste message from the error window (if any)**
![image](https://user-images.githubusercontent.com/92024598/136253395-e0a3fd17-75d3-4169-93ab-fa9ed9438b1f.png)

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - OS: Windows 10, 12 cores, 98 GB RAM

**Details about your Mesmerize install**
using anaconda pip install 21.0.1

**Additional context**

Thanks in advance!!

**Comment by kushalkolar** [comment]
@DanielDondorp this seems windows specific, any ideas? Related to the way windows does forking?

Fastest solution is probably to just use threading if windows, multiprocessing if not windows.

**Comment by DanielDondorp** [comment]
I vaguely remember that you can make non-daemonic pools. Doing that to the top-level here would solve this I think. I can't look into it deeply right now but I will have a look tomorrow.

**Comment by DanielDondorp** [comment]
Sorry, I am a bit confused now. It is supposed to be: `import multiprocessing.pool.ThreadPool as Pool`. The error you get suggests that you wrote `multiprocess` and not `multiprocessing` in the file.

**Comment by kushalkolar** [comment]
closing, you're welcome to re-open if you still have issues or post a new issue.
