### ISSUE TITLE
Improve CNMF with evenly lighted recordings?

### ISSUE THREAD

**Issue by TundeSzungyi** [kushalkolar/MESmerize#75]
**Many false negative and false positive results of CNMF**

Hi,

I have a problem, that even though I tried very different parameters with CMNF some neurons are not found and at some places, there is a very big amount marked, which creates false-positive results. I attached my photo of my CNMF results (I tried different neuron sizes, SNR, neuron numbers per patch).

The boundaries of the miniscope recordings are darker and I was thinking that maybe this is the problem, because I got stuck that so many neurons are not found. 

**Do I need to make some preprocessing of the videos, are there some methods that I could use? Or should I look for parts that have the same lightning and crop those parts to analyze further?**

Here is my screenshot:
![image](https://user-images.githubusercontent.com/61975007/141683651-f0b65687-dbac-4755-99e1-6281919930e1.png)

Thank you very much in advance

**Comment by kushalkolar** [comment]
You will need to use CNMFE for 1p data.

**Comment by TundeSzungyi** [comment]
Thank you!
