### ISSUE TITLE
Compnent registartion across multiple sessions

### ISSUE THREAD

**Issue by TundeSzungyi** [kushalkolar/MESmerize#76]
**Component registration across multiple sessions.**

Hi,

I need MESmerize to follow neural activity in long-term measurements. Is there a feature for that to annotate the same neurons in multiple recordings with the same number to compare them later on?

Thank you in advance.

**Comment by kushalkolar** [comment]
@TundeSzungyi You can use `caiman` directly for ROI registration across sessions.

This notebook describes how to interact with batch manager outputs :
https://github.com/kushalkolar/MESmerize/blob/master/notebooks/demo_batch_ingestion.ipynb

You can use those outputs with `caiman` to perform registration:
https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_multisession_registration.ipynb
