### ISSUE TITLE
unexpected issues to a new man

### ISSUE THREAD

**Issue by PPPPolish** [kushalkolar/MESmerize#86]
**Describe the bug**
the following error occurred

KeyError: ('No framerate for current image sequence!', 'You must set a framerate for the current image sequence. You can set it manually in the console like this:\nget_meta()["fps"] = <framerate>')

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to 'set CNMF parameters'
2. Click on 'Add to batch'
3. See error  above

Indeed I run ''' get_meta()["fps"] = 1 ''' in the Console at Mesmerize- Welcome Window-
**Expected behavior**

 Traceback (most recent call last):
      File "/home/user/venvs/mesmerize/lib/python3.6/site-packages/mesmerize/pyqtgraphCore/console/Console.py", line 167, in execSingle
        output = eval(cmd, self.globals(), self.locals())
      File "<string>", line 1
        get_meta()["fps"] = 1
                          ^
    SyntaxError: invalid syntax
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/venvs/mesmerize/lib/python3.6/site-packages/mesmerize/pyqtgraphCore/console/Console.py", line 171, in execSingle
        exec(cmd, self.globals(), self.locals())
      File "<string>", line 1, in <module>
    NameError: name 'get_meta' is not defined

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
OS: the xubantu posted online, containing mesmerize

**Details about your Mesmerize install**
  - Are you using anaconda or venv (the python built-in virtual environment management)
  - Are you using the pip install, If so which version?**
  - Are you using a clone of the master branch from the GitHub repo installed in development mode?

**Additional context**

**Comment by kushalkolar** [comment]
You need to run that in the Viewer console, my guess is that you ran this
in the welcome window console.

**Comment by PPPPolish** [comment]
THANK YOU for your advice
But  I am able not to find the console in the Viewer  and I paste the screenshot here

https://user-images.githubusercontent.com/63966145/156511631-a0ce113a-40a5-4a9c-9276-4c5333bfc4e6.png

**Comment by kushalkolar** [comment]
http://docs.mesmerizelab.org/en/master/user_guides/viewer/overview.html#console

**Comment by kushalkolar** [comment]
@PPPPolish did you figure it out? You're welcome to re-open or post a new issue if you have more questions.
