### ISSUE TITLE
restricting CNMF ROI detection to specific regions of the image

### ISSUE THREAD

**Issue by pr4deepr** [kushalkolar/MESmerize#96]
Hi guys

  I have a question about performing CNMF detection. I would like to perform the ROI detection on an area of interest. 
For example, the highlighted area with dotted lines in this image:
![Screenshot from 2022-03-29 12-27-50](https://user-images.githubusercontent.com/13831458/160514184-c18d4a05-36a1-4fb1-b9cc-261e436d5d07.png)
[Source](https://www.gastrojournal.org/article/S0016-5085(08)02316-0/fulltext)
 
Is there a way to do this in MESmerize? I may have a larger field of view with similar structures and may want to restrict detection to similar structures. How do I go about it? 

Cheers
Pradeep

**Comment by kushalkolar** [comment]
@pr4deepr This is a pretty specific use case. I would perform CNMF On the entire FOV, get the center of mass for each spatial component and filter the ones that are outside the larger ROI.
